language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
addons:
  code_climate:
    repo_token:
      secure: "XejmqWzHwWygA+Tx0WYs4JI1BQgu9DAZdWbgKkPfBiIquZYJsVNQgSyI10QDOCerU0+RliS+lv7ignuVswPXfLYeQIRocUjLEUJzKhB2Gblbp/s/QiHYH4nULFUfH0cq18aECPuIQgUIWB9ZUky5TMtE/xKZ+vAOtpS85+Ksd/s="
before_script:
- make travis-init
script:
- make travis-run
after_success:
- make travis-report
