language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
addons:
  code_climate:
    repo_token:
      secure: "XejmqWzHwWygA+Tx0WYs4JI1BQgu9DAZdWbgKkPfBiIquZYJsVNQgSyI10QDOCerU0+RliS+lv7ignuVswPXfLYeQIRocUjLEUJzKhB2Gblbp/s/QiHYH4nULFUfH0cq18aECPuIQgUIWB9ZUky5TMtE/xKZ+vAOtpS85+Ksd/s="
before_script:
- COMPOSER_ROOT_VERSION=dev-master
- composer self-update
- composer install
- mkdir -p build/logs
script:
- phpunit --coverage-clover build/logs/clover.xml
after_script:
- php vendor/bin/coveralls
- php vendor/bin/test-reporter --stdout > codeclimate.json
- ! 'curl -X POST -d @codeclimate.json -H "Content-Type: application/json" -H "User-Agent: Code Climate (PHP Test Reporter v1.0.1-dev)"  https://codeclimate.com/test_reports'
